# Exploratory Data Anlysis for Video Game Sales Dataset

In [53]:
#Import the EDA packages
import pandas as pd
import numpy as np
from scipy import stats

In [55]:
df = pd.read_csv('vgames.csv')

In [57]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [59]:
#check for missing values
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [61]:
#drop missing values
df = df.dropna()

In [63]:
df['Platform'].value_counts()

Platform
DS      2131
PS2     2127
PS3     1304
Wii     1290
X360    1234
PSP     1197
PS      1189
PC       938
XB       803
GBA      786
GC       542
3DS      499
PSV      410
PS4      336
N64      316
SNES     239
XOne     213
SAT      173
WiiU     143
2600     116
NES       98
GB        97
DC        52
GEN       27
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

In [65]:
#Create a dictionary to identify the manufacturer for each platform represented in the data set
console_to_company = {
    # Nintendo
    "GB": "Nintendo", "NES": "Nintendo", "WiiU": "Nintendo", "SNES": "Nintendo", "N64": "Nintendo", "3DS": "Nintendo", "GC": "Nintendo", 
    "GBA": "Nintendo", "Wii": "Nintendo", "DS": "Nintendo",

    # Sony
    "PS": "Sony", "PS2": "Sony", "PS3": "Sony", "PS4": "Sony", "PSP": "Sony", "PSV": "Sony",

    # Microsoft
    "XB": "Microsoft",  "X360": "Microsoft", "XOne": "Microsoft",

    # PC
    "PC": "PC",
    
    # Sega
    "GEN": "Sega",  "DC": "Sega", "SAT": "Sega",

    # Atari
    "2600": "Atari"
}


Video_Game_Company = pd.DataFrame(list(console_to_company.items()), columns=["Platform", "Video Game Company"])
print(Video_Game_Company)

   Platform Video Game Company
0        GB           Nintendo
1       NES           Nintendo
2      WiiU           Nintendo
3      SNES           Nintendo
4       N64           Nintendo
5       3DS           Nintendo
6        GC           Nintendo
7       GBA           Nintendo
8       Wii           Nintendo
9        DS           Nintendo
10       PS               Sony
11      PS2               Sony
12      PS3               Sony
13      PS4               Sony
14      PSP               Sony
15      PSV               Sony
16       XB          Microsoft
17     X360          Microsoft
18     XOne          Microsoft
19       PC                 PC
20      GEN               Sega
21       DC               Sega
22      SAT               Sega
23     2600              Atari

In [67]:
df.loc[:, "Video Game Company"] = df["Platform"].map(console_to_company)

/var/folders/8w/5949xr0n5_dby4vc47tq98lc0000gn/T/ipykernel_26959/3884955324.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, "Video Game Company"] = df["Platform"].map(console_to_company)

In [69]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Video Game Company
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,Nintendo
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,Nintendo
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,Nintendo
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,Nintendo
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,Nintendo
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,Nintendo
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,Sony
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,Nintendo
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,Nintendo

In [71]:
df['Video Game Company'].value_counts()

Video Game Company
Sony         6563
Nintendo     6141
Microsoft    2250
PC            938
Sega          252
Atari         116
Name: count, dtype: int64

In [84]:
#Create another dictionary for separating platforms into their respective console generations. I did not include handheld platforms or PC for consideration as they are routinely not numbered in the same generational terms.
VG_Generation = {
    # 8th
    "WiiU": "8th", "PS4": "8th", "XOne": "8th",

    # 7th
    "PS3": "7th", "Wii": "7th", "X360": "7th",

    # 6th
    "PS2": "6th", "XB": "6th", "GC": "6th", "DC": "6th",

    # 5th
    "PS": "5th", "N64": "5th", "SAT": "5th",
    
    # 4th
    "GEN": "4th",  "SNES": "4th", "NG": "4th", "TG16": "4th",

    # 3rd
    "NES": "3rd",

    # 2nd
    "2600": "2nd"
}

Generation = pd.DataFrame(list(VG_Generation.items()), columns=["Platform", "Generation"])
print(VG_Generation)

{'WiiU': '8th', 'PS4': '8th', 'XOne': '8th', 'PS3': '7th', 'Wii': '7th', 'X360': '7th', 'PS2': '6th', 'XB': '6th', 'GC': '6th', 'DC': '6th', 'PS': '5th', 'N64': '5th', 'SAT': '5th', 'GEN': '4th', 'SNES': '4th', 'NG': '4th', 'TG16': '4th', 'NES': '3rd', '2600': '2nd'}

In [86]:
#Map console generation to corresponding platforms in the data frame
df.loc[:, "Console Generation"] = df["Platform"].map(VG_Generation)

In [88]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Video Game Company,Console Generation
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,Nintendo,7th
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,Nintendo,3rd
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,Nintendo,7th
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,Nintendo,7th
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,Nintendo,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,Nintendo,NaN
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,Nintendo,6th
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,Sony,6th
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,Nintendo,NaN
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,Nintendo,NaN

In [79]:
#export for further EDA using Tableau Public
df.to_csv('games_final.csv', index=False)